import Head from "next/head";
import { useState } from "react";
import { useLazyQuery } from "@apollo/client";
import { GET_CHARS_BY_NAME } from "../graphql/queries";
import List from "../components/List";

const PesquisaPage = () => {
  const [name, setName] = useState("");

  const [getCharsByName, { loading, error, data }] =
    useLazyQuery(GET_CHARS_BY_NAME);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container pt-8 px-4 md:px-9">
        <div className="flex justify-center items-center mb-8">
          <div>
            <input
              class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight  focus:shadow-outline"
              id="username"
              type="text"
              placeholder="Personagem"
              onChange={(e) => setName(e.target.value)}
            />
          </div>
          <button
            class="bg-cyan-500 hover:bg-cyan-600 text-white font-bold py-2 px-4 rounded"
            onClick={() => getCharsByName({ variables: { name } })}
          >
            Buscar
          </button>
        </div>
      </div>

      <div className="container">
        {loading && "...Carregando"}
        <List list={data?.characters?.results} />
      </div>
    </>
  );
};

export default PesquisaPage;
